- type: job
  id: ChiefTechnicalSpecialist
  name: job-name-chief-technical-specialist
  description: job-description-chief-technical-specialist
  playTimeTracker: JobChiefTechnicalSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: EngineeringTechnicalService
    time: 54000
  weight: 940
  icon: JobChiefTechnicalSpecialist
  supervisors: job-supervisors-director
  radioBold: true
  displayWeight: 70
  canBeAntag: true
  accessGroups:
  - ChiefTechnicalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Four
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - EngineeringTechnicalService
      includeJobName: true
    - type: ScpRepairableCanSeeExamineHints

- type: startingGear
  id: ChiefTechnicalSpecialistGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskGas
    neck: ClothingNeckScarfCe
    outerClothing: ClothingOuterWinterColorWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    gloves: ClothingHandsGlovesFingerlessInsulated
    shoes: ClothingShoesColorBrown
    back: ClothingBackpackCE
    id: KeyCardChiefTechnicalSpecialist
    ears: ClothingHeadsetAltEngineeringTechnicalService
    belt: ClothingBeltUtilityEngineering
    pocket2: ChiefTechnicalSpecialistPDA
  storage:
    back:
    - Flash
    - Telebaton
