- type: job
  id: ScientificServiceDirector
  name: job-name-scientific-service-director
  description: job-description-scientific-service-director
  playTimeTracker: JobScientificServiceDirector
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 54000
  weight: 960
  icon: JobScientificServiceDirector
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 50
  accessGroups:
  - ScientificServiceDirector
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Four
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - ScientificService
      includeJobName: true
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: ScientificServiceDirectorGear
  equipment:
    id: KeyCardScientificServiceDirector
    pocket1: HandheldRoboAnalyzer
    pocket2: ScientificServiceDirectorPDA
    ears: ClothingHeadsetAltScientificService
  storage:
    back:
    - Flash
    - Telebaton
