- type: job
  id: SeniorLogisticsOfficer
  name: job-name-senior-logistics-officer
  description: job-description-senior-logistics-officer
  playTimeTracker: JobSeniorLogisticsOfficer
  requirements:
  - !type:RoleTimeRequirement
    role: JobLogisticsOfficer
    time: 36000
  weight: 935
  icon: JobSeniorLogisticsOfficer
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 40
  accessGroups:
  - SeniorLogisticsOfficer
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - LogisticsService
      includeJobName: true

- type: startingGear
  id: SeniorLogisticsOfficerGear
  equipment:
    head: ClothingHeadBandOrange
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGasExplorer
    neck: ClothingNeckScarfQm
    outerClothing: ClothingOuterWinterMiner
    jumpsuit: ClothingUniformJumpsuitQM
    gloves: ClothingHandsGlovesColorLightBrown
    shoes: ClothingShoesColorBrown
    id: KeyCardSeniorLogisticsOfficer
    ears: ClothingHeadsetAltLogistics
    pocket1: AppraisalTool
    pocket2: SeniorLogisticsOfficerPDA
