- type: job
  id: LeadTechnicalSpecialist
  name: job-name-lead-technical-specialist
  description: job-description-lead-technical-specialist
  playTimeTracker: JobLeadTechnicalSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineeringTechnicalService
      time: 36000
  icon: JobLeadTechnicalSpecialist
  supervisors: job-supervisors-chief-technical-specialist
  displayWeight: 30
  weight: 755
  accessGroups:
  - LeadTechnicalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpRepairableCanSeeExamineHints

- type: startingGear
  id: LeadTechnicalSpecialistGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWinterColorRed
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    gloves: ClothingHandsGlovesFingerlessInsulated
    shoes: ClothingShoesColorBrown
    back: ClothingBackpackEngineering
    id: KeyCardLeadTechnicalSpecialist
    ears: ClothingHeadsetEngineeringTechnicalService
    belt: ClothingBeltUtilityEngineering
    pocket2: ScpEngineeringPDA
