- type: job
  id: HospitalIntern
  name: job-name-hospital-intern
  description: job-description-hospital-intern
  playTimeTracker: JobHospitalIntern
  icon: JobHospitalIntern
  supervisors: job-supervisors-head-of-medical-sector
  canBeAntag: true
  displayWeight: 0
  weight: 760
  accessGroups:
  - CommonMedicalJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
  # Интерн исключение из врачей, он пугается трупов, потому что слишком неопытен.

- type: startingGear
  id: HospitalInternGear
  equipment:
    head: ClothingHeadHatRedsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterileRed
    neck: ClothingNeckScarfStripedRed
    jumpsuit: ClothingUniformJumpsuitColorWhite
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    id: KeyCardHospitalIntern
    ears: ClothingHeadsetMedicalService
    belt: ClothingBeltMedicalFilled
    pocket1: BookMedicalReferenceBook
    pocket2: ScpMedicalPDA
