- type: job
  id: MedicalSpecialist
  name: job-name-medical-specialist
  description: job-description-medical-specialist
  playTimeTracker: JobMedicalSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 7200
  icon: JobMedicalSpecialist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 20
  weight: 770
  accessGroups:
  - CommonMedicalJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: MedicalSpecialistGear
  equipment:
    head: ClothingHeadHatRedsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterileRed
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    id: KeyCardMedicalSpecialist
    ears: ClothingHeadsetMedicalService
    belt: ClothingBeltMedicalFilled
    pocket2: ScpMedicalPDA
