- type: job
  id: PharmaceuticalSpecialist
  name: job-name-pharmaceutical-specialist
  description: job-description-pharmaceutical-specialist
  playTimeTracker: JobPharmaceuticalSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 10800
  icon: JobPharmaceuticalSpecialist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 30
  weight: 775
  accessGroups:
  - PharmaceuticalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: PharmaceuticalSpecialistGear
  equipment:
    head: ClothingHeadHatRedsoft
    eyes: ClothingEyesGlassesChemical
    mask: ClothingMaskSterileRed
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterCoatLab
    jumpsuit: ClothingUniformJumpsuitChemistry
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    id: KeyCardPharmaceuticalSpecialist
    ears: ClothingHeadsetMedicalService
    belt: ChemBag
    pocket1: HandLabeler
    pocket2: ScpMedicalPDA
