- type: job
  id: Psychotherapist
  name: job-name-psychotherapist
  description: job-description-psychotherapist
  playTimeTracker: JobPsychotherapist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200
  icon: JobPsychotherapist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 10  # Sunrise
  weight: 765
  accessGroups:
  - CommonMedicalJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two

- type: startingGear
  id: PsychotherapistGear
  equipment:
    eyes: ClothingEyesGlasses
    mask: ClothingMaskBreathMedical
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterCoatLab
    jumpsuit: ClothingUniformJumpsuitPsychologist
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesLeather
    back: ClothingBackpackMedical
    id: KeyCardPsychotherapist
    ears: ClothingHeadsetMedicalService
    pocket2: ScpMedicalPDA
