- type: job
  id: ProductionSpecialist
  name: job-name-production-specialist
  description: job-description-production-specialist
  playTimeTracker: JobProductionSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 10800
  - !type:DepartmentTimeRequirement
    department: EngineeringTechnicalService
    time: 10800
  icon: JobProductionSpecialist
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 10
  weight: 790
  accessGroups:
  - ProductionSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: ProductionSpecialistGear
  equipment:
    head: ClothingHeadHatCorpsoft
    neck: ClothingNeckTieSci
    jumpsuit: ClothingUniformJumpsuitRoboticist
    outerClothing: ClothingOuterCoatRobo
    shoes: ClothingShoesColorWhite
    back: ClothingBackpackScience
    id: KeyCardProductionSpecialist
    ears: ClothingHeadsetScientificService
    pocket2: ScpResearchPDA
