- type: job
  id: SeniorHeavyContainmentZoneOfficer
  name: job-name-senior-heavy-containment-zone-officer
  description: job-description-senior-heavy-containment-zone-officer
  playTimeTracker: JobSeniorHeavyContainmentZoneOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: HeavyContainmentSecurityService
    time: 36000
  icon: JobSeniorHeavyContainmentZoneOfficer
  supervisors: job-supervisors-heavy-containment-zone-commandant
  canBeAntag: false
  displayWeight: 10
  weight: 840
  accessGroups:
  - SecurityJobCommon
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: SpeakOnEyeStateChange # переопределение моргания с другими параметрами для охраны и МОГа
      # Часть фраз уходит, так как более разговорная. А эти парни натренированы.
      phraseOnClose:
      - close-eye-phrase-1
      - close-eye-phrase-3
      - close-eye-phrase-4
      phraseOnOpen:
      - open-eye-phrase-1
      - open-eye-phrase-3
      speakOnlyInScp173Chamber: false
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: SeniorHeavyContainmentZoneOfficerGear
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesGlassesSecurityGuard
    mask: ClothingMaskSecurityBandBlack
    neck: ClothingNeckMantleSecurity
    jumpsuit: ClothingUniformSecurityBlack
    outerClothing: ClothingOuterArmorSecurity
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesBootsSecurityGuard
    back: ClothingBackpackSecurity
    suitstorage: WeaponSubMachineGunMP5
    id: KeyCardSeniorHeavyContainmentZoneOfficer
    ears: ClothingHeadsetHeavyContainmentSecurityService
    belt: ScpClothingBeltSecurityWebbingFilled
    pocket1: WeaponPistolG22
    pocket2: ScpSecurityPDA
