- type: loadout
  id: ScpLoadoutKeyCardProductionSpecialist
  equipment:
    id: KeyCardProductionSpecialist

- type: loadoutGroup
  id: ScpLoadoutGroupIdKeyCardProductionSpecialist
  name: loadout-group-id
  hidden: true
  loadouts:
  - ScpLoadoutKeyCardProductionSpecialist
