- type: job
  id: ExternalAdministrativeZoneCommandant
  name: job-name-external-administrative-zone-commandant
  description: job-description-external-administrative-zone-commandant
  playTimeTracker: JobExternalAdministrativeZoneCommandant
  requirements:
  - !type:DepartmentTimeRequirement
    department: ExternalAdministrativeZoneSecurityService
    time: 43200
  icon: JobExternalAdministrativeZoneCommandant
  supervisors: job-supervisors-security-commander
  canBeAntag: false
  displayWeight: 70
  weight: 825
  accessGroups:
  - SecurityCommandant
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpAnnounceOnSpawn
      text: squad-commander-announce-on-spawn
      channels:
      - ExternalAdministrativeZoneSecurityService
      includeJobName: true
    - type: SpeakOnEyeStateChange # переопределение моргания с другими параметрами для охраны и МОГа
      # Часть фраз уходит, так как более разговорная. А эти парни натренированы.
      phraseOnClose:
      - close-eye-phrase-1
      - close-eye-phrase-3
      - close-eye-phrase-4
      phraseOnOpen:
      - open-eye-phrase-1
      - open-eye-phrase-3
      speakOnlyInScp173Chamber: false
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: ExternalAdministrativeZoneCommandantGear
  equipment:
    head: ClothingHeadHatCapLeatherSquadLeader
    eyes: ClothingEyesGlassesSecurity
    mask: ClothingMaskSecurityBandBlack
    neck: ClothingNeckMantleSecurity
    jumpsuit: ClothingUniformJumpsuitSquadLeader
    outerClothing: ClothingOuterArmorSecurity
    gloves: ClothingHandsGlovesColorBlackAlt
    shoes: ClothingShoesBootsSecurityGuard
    back: ClothingBackpackSecurity
    suitstorage: WeaponSubMachineGunMP7
    id: KeyCardLightContainmentZoneSecurityCommandant
    ears: ClothingHeadsetAltExternalAdministrativeZoneSecurityService
    belt: ScpClothingBeltSecurityWebbingFilled
    pocket1: WeaponTaser
    pocket2: ScpSecurityPDA
  storage:
    back:
    - ScpRadioHandheldSecurityEnabled
