- type: job
  id: GastronomicSpecialist
  name: job-name-gastronomic-specialist
  description: job-description-gastronomic-specialist
  playTimeTracker: JobGastronomicSpecialist
  icon: JobGastronomicSpecialist
  supervisors: job-supervisors-personnel-officer
  weight: 735
  access:
  - Service
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: GastronomicSpecialistGear
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlasses
    outerClothing: ClothingOuterApronChef
    jumpsuit: ClothingUniformJumpsuitChef
    shoes: ClothingShoesColorBlack
    back: ClothingBackpack
    id: KeyCardGastronomicSpecialist
    ears: ClothingHeadsetFoodAndSanitation
    belt: ClothingBeltChefFilled
    pocket2: ScpServicePDA
