# Copied for _Scp role loadouts.

- type: loadout
  id: ScpHeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
  groupBy: "jumpsuit"

- type: loadout
  id: ScpHeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS
  groupBy: "jumpskirt"

- type: loadout
  id: ScpHeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt
  groupBy: "jumpsuit"

- type: loadout
  id: ScpHeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt
  groupBy: "jumpskirt"

- type: loadout
  id: ScpHeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal
  groupBy: "jumpsuit"

- type: loadout
  id: ScpHeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal
  groupBy: "jumpskirt"

#Sunrise-Start

- type: loadout
  id: ScpHeadofSecurityJumpsuitHoSOld
  sponsorOnly: false
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSOld
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: ScpHeadofSecurityJumpsuitUSSPBlack
  sponsorOnly: false
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSPBlack
#Sunrise-End

# Head

- type: loadout
  id: ScpHeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: ScpHeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

#Sunrise-Start

- type: loadout
  id: ScpHeadofSecurityHatCap
  equipment:
    head: ClothingHeadHatCapHoS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: ScpHeadofSecurityCapUSSPBlack
  sponsorOnly: false
  equipment:
    head: ClothingHeadHatCapUSSPBlack

- type: loadout
  id: ScpHeadofSecurityCapLeather
  sponsorOnly: false
  equipment:
    head: ClothingHeadHatCapLeatherHoS
#Sunrise-End

# Neck

- type: loadout
  id: ScpHeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: ScpHeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: ScpHeadofSecurityCloakHOSCloak
  sponsorOnly: false
  equipment:
    neck: ClothingNeckCloakHOSCloak

- type: loadout
  id: ScpHeadofSecurityDarthHOSCloak
  sponsorOnly: false
  equipment:
    neck: ClothingNeckCloakDarthHOSCloak
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

# OuterClothing

- type: loadout
  id: ScpHeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: ScpHeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

#Sunrise-Start

- type: loadout
  id: ScpHeadofSecurityGreatcoat
  equipment:
    outerClothing: ClothingOuterCoatHoSGreatcoat
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: ScpHeadofSecurityGreatcoatBlack
  sponsorOnly: false
  equipment:
    outerClothing: ClothingOuterCoatHOSOvercoatBlack
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: ScpHeadofSecurityUSSPBlack
  sponsorOnly: false
  equipment:
    outerClothing: ClothingOuterCoatUSSPOvercoatBlack

- type: loadout
  id: ScpHeadofSecurityOvercoat
  sponsorOnly: false
  equipment:
    outerClothing: ClothingOuterCoatHoSOvercoat
#Sunrise-End
